<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Remember Me_form-check-input</name>
   <tag></tag>
   <elementGuidId>288add7b-a4eb-4bbf-9fca-894a1b25d496</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.form-check-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='checkbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6537abc3-57ee-4611-a366-4fb9e1ef134f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>66f07831-65e0-49f0-bc99-e282a517d0eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>f2746888-79fc-45e3-adc9-fa6655862959</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;auth-wrapper&quot;]/div[@class=&quot;all-wrapper menu-side with-pattern&quot;]/div[@class=&quot;auth-box-w&quot;]/form[1]/div[@class=&quot;buttons-w&quot;]/div[@class=&quot;form-check-inline&quot;]/label[@class=&quot;form-check-label&quot;]/input[@class=&quot;form-check-input&quot;]</value>
      <webElementGuid>be04059a-820c-434a-be7c-b5b91a373f60</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='checkbox']</value>
      <webElementGuid>8a15ceed-5dda-4137-a6a4-7cefcb3d2f41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>5a03ad38-837b-4fd2-b925-7d7ce6bf7e80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>d2ca11ca-0885-43f1-b35b-d380105f1a54</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
